protein_sequence = "MHEITCFPLQSPSYIQDYMWTAATSFKYCCRWDCGFKACFLHYTISPQRHNWMIQHSPWYEWSQKFNNECSSDCVYGLAYQTVQDLSDANNYKWHLVFRAFFFYHQRNYVKRMMLSDTFISSCWFQKLKRNERRYAQDRKYENQVVKTEMQNRMRDKQGSHHWTYFAQEAMSYEPRSIAVNKCPMFQPKFDITRVEVQSCWHEEVAKFSCLPISGKMKSGPANTQLCFFASLVEAANHVTQCKWDKENCEMKAEVHVHCMKCEFNMCQSGAYTCFYLWSFQQGPPHCTGGREDILSDQWKWMAQNIMVPNAGTYYECQIKIYHNSDWNCCERPMRALQSIQFEYADHPPQEQTLAGNADMAHLRRQHHYISQGNHQCRVVNCSLEARKLPKCLTYDYSAWTPRFWQKYRYTLDFYVIQLIMCQSARGDHQHYSKDETFQKQPHDKLFARCVFRPLPNRTLTKLIDQRVHMETVQWWHVACDFHWNCSNGPNDAQMFFWRAKCDMHVEEVEDKPNWIHKWCQIETSMFVGSKPNNRILWMNTECHNELINQFSYNAGEHYHIDCARMKVLCESVFTKSSAKWAHVPPVHTKYFALNHNVCNATNGHQGDYDGCEWPEDADARNNRGCNGKSMTAIQNPTGKQELEIFTGCMWQKHNDVIGPKPQQEHIMRQIPKKYCRWLLECHKYFWLWFKLTDHTSDQLVTRDQIMHAFTSIWNRLQVCEMFQYNGQFDYWSHMMTHFEANKDCLHHGFCRAPSRRCKGWMKVSWLEPHELECPYWFPKFECHSVILNFCRDKRLWCAWDIQGRTRTAYYPCPRDFIRRSKWQYEWIIKWNIEFQQNVHPFRYYAEVMRTGRMYEPAGQPECYMNPFWIWMCNPGVWRTNKLQYFNNRQCNMRHTFNYMRNFWIKTVKAMCTCSFPYWQVNIGAGGLNFSNNFVVKYMCYISGDRWHLCTEDVIKWDPVMPDLETDAGPYQCTCDRDLKRFSLDIYISMTCMGSMH "

def inferring(protein_sequence):
    possibilities_temp = 0
    possibilities = 1
    MOD = 1000000
    codon_table = {
        'UUU': 'F', 'UUC': 'F', 'UUA': 'L', 'UUG': 'L',
        'CUU': 'L', 'CUC': 'L', 'CUA': 'L', 'CUG': 'L',
        'AUU': 'I', 'AUC': 'I', 'AUA': 'I', 'AUG': 'M',
        'GUU': 'V', 'GUC': 'V', 'GUA': 'V', 'GUG': 'V',
        'UCU': 'S', 'UCC': 'S', 'UCA': 'S', 'UCG': 'S',
        'AGU': 'S', 'AGC': 'S',
        'CCU': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P',
        'ACU': 'T', 'ACC': 'T', 'ACA': 'T', 'ACG': 'T',
        'GCU': 'A', 'GCC': 'A', 'GCA': 'A', 'GCG': 'A',
        'UAU': 'Y', 'UAC': 'Y', 'UAA': ' ',  'UAG': ' ',
        'CAU': 'H', 'CAC': 'H', 'CAA': 'Q', 'CAG': 'Q',
        'AAU': 'N', 'AAC': 'N', 'AAA': 'K', 'AAG': 'K',
        'GAU': 'D', 'GAC': 'D', 'GAA': 'E', 'GAG': 'E',
        'UGU': 'C', 'UGC': 'C', 'UGA': ' ',  'UGG': 'W',
        'CGU': 'R', 'CGC': 'R', 'CGA': 'R', 'CGG': 'R',
        'AGA': 'R', 'AGG': 'R', 'GGU': 'G', 'GGC': 'G',
        'GGA': 'G', 'GGG': 'G'
    }

    for AS in protein_sequence:
        if AS in codon_table.values():
            for codon in codon_table:
                if codon_table[codon] == AS:
                    possibilities_temp += 1
            if possibilities_temp != 0:
                possibilities = possibilities * possibilities_temp
                possibilities_temp = 0
    return possibilities % MOD

print(inferring(protein_sequence))