dna = "GCGCGTCTTGCGCCGGGTAGAGCCTCTCTGCCGTCCCCAGCCACCCGCATTGTGCGTAGGTGTTAACGGCTCGAGAAGGGCTAGTGATTTACACGATTTAATCCCACACTTCCCTCGATCGCGGGATCCATGGCCGGGCTCCGTCCCCGTTCTTATCGTGGAATCAAAAGGAATAACATGAACTCTACAATACTGTACCTTCACCGACCCGCGGGAGTTGCTGTGCAGTAAACGGCCAGACATGGCCATTTGATGATCAAACTTCCACGTTTGCAAGTTGCAGTGCATAGGGTGCCATCCCCCAGTTATGCAGAACACGTACCTCCCACTCGGACTAGCCCCGTGACACATGTACTGGGCTCGCGTGGCTTGGCGGAAGTGCAGAGTCGGGAATTTAGAGCCAAAAAACCGTGCGACACTTAAAACTTAGGATCCAACGTTAGGGTCAGGACCGTGTGTCGCGCGACAGCAGTAGGGAACTTTGCGGGCAGACCTCTTCAAGTTGGCCCGTGCGAGGGAAAGTGCAAAAACCGGTTGGCCTTACAGTATCCGGGCATGTTAGACGCCGTACTAGAACCTAAAGGTCTCCTAAGCGTGCACAAGCACAGTGATTTTTTAGCCTCAGATAAAGTGGGGACGTACATATTCGGTAAGGGTCGGACTTTTCTTCCACACGACCCCGGCTCTGCACCGAGGTTTGTAGGGTGCCTTACTCATATATTCAGCGATAACAGACTCAGCGCCGATTGTAAAAAATCTATATAAAGGGTTTACGAACTTGTTATCGTCGCTGACTTTGGTAGCCGAAAACCGCATAGGACGAGTTACGGTGGGTCCCGGGGCCCGGAAGACTTTACGAACACGACTAGACCGACAAGGGAGGGTTTTCAATGTCGTCTCTAGCCTATCAATTCTAAAGATATA"

def reverse_complement(s):
    comp = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    return ''.join(comp[c] for c in reversed(s))


def find_reverse_palindromes(dna):
    results = []
    n = len(dna)

    for i in range(n):
        for length in range(4, 13):
            if i + length <= n:
                fragment = dna[i:i + length]
                if fragment == reverse_complement(fragment):
                    results.append((i + 1, length))  # 1-based index

    return results

for pos, length in find_reverse_palindromes(dna):
    print(pos, length)